name:                edit-distance-linear
version:             0.2.0.0
github:              "0xd34df00d/edit-distance-linear"
license:             BSD3
author:              "Georg Rudoy"
maintainer:          "0xd34df00d@gmail.com"
copyright:           "2019 Georg Rudoy"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Efficient implementation Levenshtein distance in linear memory.
category:            Algorithms

description:         Please see the README on GitHub at <https://github.com/0xd34df00d/edit-distance-linear#readme>

dependencies:
- base >= 4.7 && < 5
- array
- bytestring

flags:
  with-executable:
    description: Build the test executable (a fast and dirty way of benchmarking, for the package development only)
    manual: true
    default: false
  llvm:
    description: Use the LLVM code generator (strongly recommended)
    manual: true
    default: true

ghc-options:
- -Wall

library:
  source-dirs: src
  when:
  - condition: flag(llvm)
    ghc-options:
    - -fllvm

benchmarks:
  edit-distance-linear-bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - edit-distance-linear
    - criterion
    - text
    - text-metrics

executables:
  edit-distance-linear-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - edit-distance-linear
    when:
    - condition: ! '!(flag(with-executable))'
      buildable: false

tests:
  edit-distance-linear-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - edit-distance-linear
    - edit-distance
    - hspec
    - QuickCheck
